# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: install the deps
        run: yarn

      - name: build the website
        run: yarn generate
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: produce artifact
        uses: actions/upload-artifact@v2
        with:
          name: website
          path: ./dist
